### ISSUE TITLE
Things to do

### ISSUE THREAD

**Issue by Ayoitsjason** [Ayoitsjason/CSC642-Human_computer_interaction_Team10#1]
##TODO
*Things left to do for Foodie APP*
* [x] Top nav bar
* [x] Middle content
* [x] Google map api
* [x] Bottom nav bar
